# Data Pre-processing
## MinMaxScaler

In [4]:
import numpy as np
from sklearn import preprocessing;

In [16]:
X_train = np.array([[1,-1,2],
                    [2,0,0],
                    [0,1,-1]])
X_test = np.array([[-1, -0.5, 2],[2, 3, -5]])

In [5]:
min_max_scaler = preprocessing.MinMaxScaler()

In [6]:
X_train_min_max = min_max_scaler.fit_transform(X_train)

/Users/Th3D4rKnight/anaconda3/envs/aarus_project/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
X_train_min_max

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

# MaxAbsScaler


In [11]:
maxAbs = preprocessing.MaxAbsScaler()
X_train_max_abs = maxAbs.fit_transform(X_train)
X_train_max_abs

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [17]:
X_test_max_abs = maxAbs.fit_transform(X_test)
X_test_max_abs

array([[-0.5       , -0.16666667,  0.4       ],
       [ 1.        ,  1.        , -1.        ]])

# Normalized

In [19]:
X_normalized = preprocessing.normalize(X_train,norm="l2")
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])